### PR TITLE
fix manifest, and get rid of an extra file

### PR DESCRIPTION
**Pull request by Laurentiu-Andronache**

### CODE REVIEW

**Comment by Matoking** [comment]
Looks good. 

There are a few small problems with tox though. `check-manifest` fails due to a missing executable. I searched around GitHub and this seems to work:

```
[tox]
envlist = py34,py35,py36,py37,check-manifest
skip_missing_interpreters = true

[testenv]
deps = pytest
commands =
    python setup.py check -m -s
    python setup.py test

[testenv:check-manifest]
deps =
    check-manifest
skip_install = true
commands = check-manifest
```

MANIFEST.in also needs the following line in order to ignore the .so files when building the sdist and to make `check-manifest` pass:

```
global-exclude *.so
```

**Comment by Laurentiu-Andronache** [comment]
oh yeah, it needs to be added to deps

**Comment by Laurentiu-Andronache** [comment]
done

**Comment by Matoking** [comment]
Everything seems to work now.

The pull request could be cleaned up a bit before merging into master, but I can also squash and merge the pull request if you prefer that instead.

**Comment by Laurentiu-Andronache** [comment]
Squash and merge.

**Comment by Matoking** [comment]
I've merged the pull request.

Thanks for your help! :+1:

**Pull request merged**
