### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by Laurentiu-Andronache**

### CODE REVIEW

**Comment by Matoking** [comment]
Thanks for the contribution.

The **requirements_dev.txt** and **tox.ini** changes look OK to me. **requirements_dev.txt** was originally added due to Travis CI having an old version of pytest preinstalled when running tests using Python 3.6, causing the test run to fail ([see here](https://travis-ci.com/Matoking/pynanocurrency/jobs/181382691)). Currently, Travis only tests with Python 3.7, even if **.travis.yml** has both 3.6 and 3.7 defined, but I'll have to look into that later. If I need to add the file again, it's better to call it **requirements_ci.txt** or something similar instead.

---

On the other hand, I don't think we should modify BLAKE2b files unless it's done upstream [in the originating repository](https://github.com/BLAKE2/BLAKE2). In hindsight those files should have been added through a git submodule instead of just copied into the repository.

**setup.py** is responsible for building each instruction set specific build, but it has only been tested on GCC so far. Can VS14 already build each module correctly except for SSE2, or do they need different compilation flags?

**Comment by Laurentiu-Andronache** [comment]
I have a lot more contributions planned! :)

You're awesome for having created this library.

VS14 builds each module correctly, even the ones that require SSE2. The problem is that the way in which it detects SSE2 support is broken, so that's why I recommended dropping that part. Right now all processors support SSE2 anyway, so that part is useless. But I can create a commit to reverse that change if you want.

Regarding the Travis config, before looking into it yourself, please have a look over the settings that I recommend in another pull request.

**Comment by Matoking** [comment]
> VS14 builds each module correctly, even the ones that require SSE2. The problem is that the way in which it detects SSE2 support is broken, so that's why I recommended dropping that part. Right now all processors support SSE2 anyway, so that part is useless. But I can create a commit to reverse that change if you want.

Interesting, have you checked using `python setup.py speed` whether there's an actual difference between the work modules, or if the compiler is just silently ignoring flags like `-mavx`? I was under the impression each compiler has vendor-specific flags for enabling those instruction sets.

I'll probably add ARM support in a future commit (the repo has a NEON implementation that could be a lot more performant), and in that case, the reference implementation for BLAKE2b can be replaced with the SSE2 version for all x86 CPUs. This should help keep the binary wheels more compact while allowing universal compatibility, whenever I get around to that.

I'm a bit unsure how to deal with Windows compatibility at the moment, as I'm not familiar with the compilers used there (multiple versions of Visual C and maybe Clang?) and what possible modifications each compiler may require. As such, I'd like to keep the C sources unedited for the time being and probably put them under a git submodule.

---

I haven't made guidelines for code contributions yet, but for now, make sure to follow [PEP 8](https://www.python.org/dev/peps/pep-0008/) in case you don't do so already.

In any case, thanks for contributing. :)

**Comment by Laurentiu-Andronache** [comment]
```
(py37) C:\Projects\Python\_helping\pynanocurrency>python setup.py speed
running speed
running speed
BLAKE2b PoW (sse2) DEFAULT speed: 2970870 hashes/s
BLAKE2b PoW (ref) speed: 2553853 hashes/s
Account generation rate: 458 accounts/s
Block sign rate: 289 blocks/s
Block verify rate: 234 blocks/s
running speed
BLAKE2b PoW (sse2) DEFAULT speed: 2812657 hashes/s
BLAKE2b PoW (ref) speed: 2119044 hashes/s
Account generation rate: 471 accounts/s
Block sign rate: 273 blocks/s
Block verify rate: 235 blocks/s
BLAKE2b PoW (sse2) DEFAULT speed: 3100826 hashes/s
BLAKE2b PoW (ref) speed: 2761750 hashes/s
Account generation rate: 498 accounts/s
Block sign rate: 277 blocks/s
Block verify rate: 232 blocks/s
```

On Windows 10, VS14.

**Comment by Matoking** [comment]
> ```
> (py37) C:\Projects\Python\_helping\pynanocurrency>python setup.py speed
> ...
> ```
> 
> On Windows 10, VS14.

What CPU are you using? What I'm interested in is seeing a difference between two different modules built using the `sse` code base. sse2, ssse3, sse4_1 and avx are built using the same source files but using different compile flags. ref on the other hand uses different source files that should work on any platform, including ARM.

For example, I'm getting these results on a Ryzen 1800X:

```
BLAKE2b PoW (avx) DEFAULT speed: 1570235 hashes/s
BLAKE2b PoW (sse4_1) speed: 1558730 hashes/s
BLAKE2b PoW (ssse3) speed: 1564134 hashes/s
BLAKE2b PoW (sse2) speed: 1161238 hashes/s
BLAKE2b PoW (ref) speed: 1138292 hashes/s
```

Note that your performance results might have been 4x higher than they were supposed to be due to an oversight I fixed a few hours ago in b69b573f.

That said, NANO is planning on moving to a memory-hard algorithm which might remove the benefit for having instruction-set specific builds ([more about it here](https://www.reddit.com/r/nanocurrency/comments/ar84o1/reminder_of_our_pow_improvement_planning/)).

**Comment by Laurentiu-Andronache** [comment]
System SKU	LENOVO_MT_80X7_BU_idea_FM_YOGA 720-15IKB
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	16.0 GB
OS Name	Microsoft Windows 10 Pro

**Comment by Matoking** [comment]
> System SKU LENOVO_MT_80X7_BU_idea_FM_YOGA 720-15IKB
> Processor Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
> Installed Physical Memory (RAM) 16.0 GB
> OS Name Microsoft Windows 10 Pro

That's weird. According to Intel's spec sheet your CPU should support all of the instruction sets, including AVX, but the library is only picking up SSE2. Could you check out what the following command prints out?

`python3 -c "import cpuinfo; print(cpuinfo.get_cpu_info()['flags'])"`

**Comment by Laurentiu-Andronache** [comment]
```
C:\Users\Nebu>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cpuinfo
>>> cpuinfo.get_cpu_info()['flags']
['3dnow', '3dnowprefetch', 'abm', 'acpi', 'adx', 'aes', 'apic', 'avx', 'avx2', 'bmi1', 'bmi2', 'clflush', 'clflushopt', 'cmov', 'cx16', 'cx8', 'de', 'ds_cpl', 'dtes64', 'dts', 'erms', 'est', 'f16c', 'fma', 'fpu', 'fxsr', 'ht', 'ia64', 'intel_pt', 'invpcid', 'lahf_lm', 'mca', 'mce', 'mmx', 'monitor', 'movbe', 'mpx', 'msr', 'mtrr', 'osxsave', 'pae', 'pat', 'pbe', 'pcid', 'pclmulqdq', 'pdcm', 'pge', 'pni', 'popcnt', 'pse', 'pse36', 'rdrnd', 'rdseed', 'sep', 'serial', 'sgx', 'smap', 'smep', 'ss', 'sse', 'sse2', 'sse4_1', 'sse4_2', 'ssse3', 'tm', 'tm2', 'tsc', 'tscdeadline', 'vme', 'vmx', 'x2apic', 'xsave', 'xtpr']
```

**Comment by Matoking** [comment]
> ```
> C:\Users\Nebu>python
> Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cpuinfo
> >>> cpuinfo.get_cpu_info()['flags']
> ['3dnow', '3dnowprefetch', 'abm', 'acpi', 'adx', 'aes', 'apic', 'avx', 'avx2', 'bmi1', 'bmi2', 'clflush', 'clflushopt', 'cmov', 'cx16', 'cx8', 'de', 'ds_cpl', 'dtes64', 'dts', 'erms', 'est', 'f16c', 'fma', 'fpu', 'fxsr', 'ht', 'ia64', 'intel_pt', 'invpcid', 'lahf_lm', 'mca', 'mce', 'mmx', 'monitor', 'movbe', 'mpx', 'msr', 'mtrr', 'osxsave', 'pae', 'pat', 'pbe', 'pcid', 'pclmulqdq', 'pdcm', 'pge', 'pni', 'popcnt', 'pse', 'pse36', 'rdrnd', 'rdseed', 'sep', 'serial', 'sgx', 'smap', 'smep', 'ss', 'sse', 'sse2', 'sse4_1', 'sse4_2', 'ssse3', 'tm', 'tm2', 'tsc', 'tscdeadline', 'vme', 'vmx', 'x2apic', 'xsave', 'xtpr']
> ```

That's weird, [performance_test.py](https://github.com/Matoking/pynanocurrency/blob/master/tests/performance_test.py#L17) should notice those flags and run the corresponding performance tests. :/

**Comment by Laurentiu-Andronache** [comment]
Huh, I thought that I had done this already. I reverted the commit for Windows compilation. You can merge now.

**Pull request closed without merging**
